"""add time_filter to topics

Revision ID: 45b017037299
Revises: dd2bac3a0c2e
Create Date: 2026-07-20 14:14:52.002165

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45b017037299'
down_revision: Union[str, Sequence[str], None] = 'dd2bac3a0c2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('topics', sa.Column('time_filter', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('topics', 'time_filter')
    # ### end Alembic commands ###
